author: Raven Tait, Splunk
id: c012bd08-cbdb-49b6-9a0d-acd51b1f1cca
date: '2025-07-09'
description: 'Sample of ESXi syslog events showing attempts to modify the syslog configuration.'
environment: custom
directory: esxi_syslog_config
mitre_technique:
- T1562.003
datasets:
- name: vmw-syslog
  path: /datasets/attack_techniques/T1562.003/esxi_syslog_config/esxi_syslog_config.log
  sourcetype: vmw-syslog
  source: vmw-syslog